In [12]:
import pandas as pd

In [26]:

df = pd.read_csv("dados_s3_sinteticos.csv")
df.describe()

        tamanho_gb  idade_dias  num_objetos  preco_por_gb  custo_mensal_usd
count   337.000000  337.000000   337.000000    337.000000        337.000000
mean    155.707270  267.258160  1672.207715      0.018352          2.384095
std     215.107716  206.949259  1135.035883      0.012865          2.710525
min       2.270000    1.000000    21.000000      0.000990          0.020000
25%      54.140000  124.000000   717.000000      0.003600          0.450000
50%     123.710000  234.000000  1597.000000      0.023000          1.460000
75%     170.390000  336.000000  2454.000000      0.023000          3.470000
max    1494.110000  899.000000  7897.000000      0.040500         13.410000

In [14]:
custo_por_bucket = df.groupby("bucket")["custo_mensal_usd"].sum().sort_values(ascending=False)
custo_por_bucket

bucket
logs-prod        302.50
ml-datasets      180.47
app-assets       127.69
data-lake-raw    100.23
backups-eu        92.55
Name: custo_mensal_usd, dtype: float64

In [15]:
custo_por_classe = df.groupby("storage_class")["custo_mensal_usd"].sum().sort_values(ascending=False)
custo_por_classe

storage_class
STANDARD                597.43
STANDARD_IA             149.08
GLACIER                  39.73
GLACIER_DEEP_ARCHIVE     17.20
Name: custo_mensal_usd, dtype: float64

In [16]:
custo_bucket_classe = df.groupby(["bucket", "storage_class"])["custo_mensal_usd"].sum().sort_values(ascending=False)
custo_bucket_classe

bucket         storage_class
logs-prod      STANDARD                255.90
ml-datasets    STANDARD                142.40
app-assets     STANDARD                 78.45
data-lake-raw  STANDARD                 63.38
backups-eu     STANDARD                 57.30
logs-prod      STANDARD_IA              38.28
app-assets     STANDARD_IA              36.16
ml-datasets    STANDARD_IA              30.43
backups-eu     STANDARD_IA              27.92
data-lake-raw  STANDARD_IA              16.29
               GLACIER_DEEP_ARCHIVE     13.44
app-assets     GLACIER                  11.08
logs-prod      GLACIER                   7.41
backups-eu     GLACIER                   7.31
data-lake-raw  GLACIER                   7.12
ml-datasets    GLACIER                   6.81
app-assets     GLACIER_DEEP_ARCHIVE      2.00
logs-prod      GLACIER_DEEP_ARCHIVE      0.91
ml-datasets    GLACIER_DEEP_ARCHIVE      0.83
backups-eu     GLACIER_DEEP_ARCHIVE      0.02
Name: custo_mensal_usd, dtype: float64

In [17]:

custo_por_region = df.groupby(["bucket","regiao"],)["custo_mensal_usd"].sum().sort_values(ascending=False)
custo_por_region

bucket         regiao
logs-prod      us-east-1    223.30
ml-datasets    sa-east-1    135.59
app-assets     sa-east-1     80.37
logs-prod      sa-east-1     79.20
data-lake-raw  us-east-1     68.24
backups-eu     us-east-1     54.83
app-assets     us-east-1     47.32
ml-datasets    us-east-1     44.88
backups-eu     sa-east-1     37.72
data-lake-raw  sa-east-1     31.99
Name: custo_mensal_usd, dtype: float64

In [28]:
df[df["bucket"] == "data-lake-raw"][["storage_class", "tamanho_gb", "custo_mensal_usd"]]

            storage_class  tamanho_gb  custo_mensal_usd
2                 GLACIER      136.25              0.49
6             STANDARD_IA       18.79              0.49
7                STANDARD       84.10              1.93
8                STANDARD      175.94              7.13
11            STANDARD_IA      123.07              1.54
..                    ...         ...               ...
320  GLACIER_DEEP_ARCHIVE     1088.49              1.08
321  GLACIER_DEEP_ARCHIVE     1184.73              1.17
322  GLACIER_DEEP_ARCHIVE     1381.37              1.37
323  GLACIER_DEEP_ARCHIVE      848.10              0.84
324  GLACIER_DEEP_ARCHIVE     1097.01              1.09

[73 rows x 3 columns]

In [27]:
df["bucket"].unique()

<StringArray>
['app-assets', 'ml-datasets', 'data-lake-raw', 'backups-eu', 'logs-prod']
Length: 5, dtype: str